#!/usr/bin/env python

import re
import sys

# IPv4 regex
ip = re.compile('((?:(?:[12]\d?\d?|[1-9]\d|[1-9])\.){3}(?:[12]\d?\d?|[\d+]{1,2}))')

input = str(sys.argv[1])
output = str(sys.argv[2])

def regex(input):
    ''' Grab only the IPs out of the file '''
    ip_list = re.findall(ip, str(input))
    return '\n'.join(ip_list)


with open(input, 'r') as file1:
    text = file1.read()
    ip_list = regex(text)
with open(output, 'w') as file2:
    file2.write(str(ip_list))




